apiVersion: v1
kind: Pod
metadata:
  name: checkly-agent
  labels:
    purpose: checkly-agent
spec:
  containers:
  - name: checkly-agent-container
    image: ghcr.io/checkly/agent:latest
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: checklysecret
          key: API_KEY