replicaCount: 2

image:
  repository: checkly/agent
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true

# -- Configures secret for agent API Key
#
# -- If you already have a secret with the Key, set `create` to
# -- false and set the `name`` value to the name of your secret.
#
# -- If you don't have a secret, set `create` to true
# -- and set the `apiKey`` value to your Key.
#
# -- You can also create a secret yourself via extraManifests[].
# -- Set `create` to false and set `name` to the name of 
# -- your secret defined in your extraManifests.
apiKeySecret:
  create: true
  apiKey: replace_me

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

extraManifests: []
