apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkly-agent
  labels:
    app: checkly-agent
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: checkly-agent
  template:
    metadata:
      labels:
        app: checkly-agent
    spec:
      containers:
        - name: checkly-agent
          image: checkly/agent:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: checklysecret
                  key: API_KEY
      terminationGracePeriodSeconds: 35
